/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Home extends javax.swing.JFrame {

   String tarik, str1, pass, trans, no;
        int choice, z ,x ,f ,n ,  pin, counter=0,a=3;
        int t,s,tab=50000,norek=31425364;
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Penarikan = new javax.swing.JToggleButton();
        ISaldo = new javax.swing.JToggleButton();
        Transfer = new javax.swing.JToggleButton();
        Bantuan = new javax.swing.JToggleButton();
        bExit = new javax.swing.JToggleButton();
        Penyetoran = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 0, 153));
        jPanel1.setForeground(new java.awt.Color(255, 0, 153));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 153));
        jLabel1.setText("TRANSAKSI");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(100, 0, 210, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 153));
        jLabel2.setText("Informasi Saldo");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(230, 90, 200, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 153));
        jLabel3.setText("Transfer");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(320, 210, 180, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 153));
        jLabel4.setText("Penarikan");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(300, 330, 180, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 153));
        jLabel5.setText("Penyetoran");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 90, 180, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 153));
        jLabel6.setText("Bantuan");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 210, 180, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 153));
        jLabel7.setText("Exit");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 330, 180, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(110, 0, 430, 420);

        Penarikan.setBackground(new java.awt.Color(255, 255, 255));
        Penarikan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Penarikan.setForeground(new java.awt.Color(255, 0, 153));
        Penarikan.setText("<");
        Penarikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenarikanActionPerformed(evt);
            }
        });
        jPanel1.add(Penarikan);
        Penarikan.setBounds(550, 320, 70, 60);

        ISaldo.setBackground(new java.awt.Color(255, 255, 255));
        ISaldo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ISaldo.setForeground(new java.awt.Color(255, 0, 153));
        ISaldo.setText("<");
        ISaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISaldoActionPerformed(evt);
            }
        });
        jPanel1.add(ISaldo);
        ISaldo.setBounds(550, 80, 70, 60);

        Transfer.setBackground(new java.awt.Color(255, 255, 255));
        Transfer.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Transfer.setForeground(new java.awt.Color(255, 0, 153));
        Transfer.setText("<");
        Transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferActionPerformed(evt);
            }
        });
        jPanel1.add(Transfer);
        Transfer.setBounds(550, 200, 70, 60);

        Bantuan.setBackground(new java.awt.Color(255, 255, 255));
        Bantuan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Bantuan.setForeground(new java.awt.Color(255, 0, 153));
        Bantuan.setText(">");
        Bantuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BantuanActionPerformed(evt);
            }
        });
        jPanel1.add(Bantuan);
        Bantuan.setBounds(30, 200, 70, 60);

        bExit.setBackground(new java.awt.Color(255, 255, 255));
        bExit.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        bExit.setForeground(new java.awt.Color(255, 0, 153));
        bExit.setText(">");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });
        jPanel1.add(bExit);
        bExit.setBounds(30, 320, 70, 60);

        Penyetoran.setBackground(new java.awt.Color(255, 255, 255));
        Penyetoran.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Penyetoran.setForeground(new java.awt.Color(255, 0, 153));
        Penyetoran.setText(">");
        Penyetoran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenyetoranActionPerformed(evt);
            }
        });
        jPanel1.add(Penyetoran);
        Penyetoran.setBounds(30, 80, 70, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 650, 570);

        setBounds(0, 0, 665, 451);
    }// </editor-fold>//GEN-END:initComponents

    private void ISaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISaldoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Saldo Anda Sebesar :" + tab);
            
    }//GEN-LAST:event_ISaldoActionPerformed

    private void PenyetoranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenyetoranActionPerformed
        // TODO add your handling code here:
         str1 = JOptionPane.showInputDialog(null,"Masukkan jumlah penyetoran: " ); //menabung
    s = Integer.parseInt(str1);
    if (s%100!=0){
        JOptionPane.showMessageDialog(null,"Mesin ATM  BRI tidak mengeluarkan uang koin "
        + "\nSilahkan ulangi kembali","Transaksi GAGAL", 0);
        }else if (s<50000) {
            JOptionPane.showMessageDialog(null,"Jumlah Penarikan Minimal Rp,50000","ERROR",0);
        }else if (s>=50000){
            JOptionPane.showMessageDialog(null,"Anda Mengambil Uang Sebesar : " + s);
            tab = tab+s;
            z=JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain?","ATM BNI SYARIAH-BOJONEGORO"
                                ,JOptionPane.YES_NO_OPTION, 3);
                if (z==0){
                    pass = JOptionPane.showInputDialog(null,"Masukkan Password : " );
                    x = Integer.parseInt(pass);
                    if(x==1234){
                        JOptionPane.showMessageDialog(null,"Password Benar, \nSilahkan Click OK");
                    }else{
                        JOptionPane.showMessageDialog(null,"Password Salah");
                    }
                }else{
                    this.dispose();
                }
            }
    }//GEN-LAST:event_PenyetoranActionPerformed

    private void BantuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BantuanActionPerformed
        // TODO add your handling code here:
        new Bantuan().show();
    }//GEN-LAST:event_BantuanActionPerformed

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        // TODO add your handling code here:
        dispose(); 
    }//GEN-LAST:event_bExitActionPerformed

    private void TransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferActionPerformed
        // TODO add your handling code here:
        no = JOptionPane.showInputDialog(null,"Masukkan Nomor Tujuan Transfer : " );
    n = Integer.parseInt(no);
    trans = JOptionPane.showInputDialog(null,"Masukkan Jumlah Yang Ditransfer : " );
    f = Integer.parseInt(trans);
        if(f<=tab && f>0){
            if (f>0){
              JOptionPane.showMessageDialog(null," Anda Transfer Sebesar : " + f + "\n Dari No.Rek : " + norek +"\n Kepada No.Rek:"+n);
                tab = tab-f;
                z=JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain?","ATM BNI SYARIAH-BOJONEGORO"
                                ,JOptionPane.YES_NO_OPTION, 3);
                if (z==0){
                    pass = JOptionPane.showInputDialog(null,"Masukkan Password : " );
                    x = Integer.parseInt(pass);
                    if(x==1234){
                        JOptionPane.showMessageDialog(null,"Password Benar, \nSilahkan Click OK");
                    }else{
                        JOptionPane.showMessageDialog(null,"Password Salah","ERROR",0);
                        dispose();
                    }
                }else{
                    this.dispose();
                }
            }
        }else{
            JOptionPane.showMessageDialog(null,"MOHON MAAF :\n1. Jumlah Saldo Anda Kurang \n2. Atau Jumlah Masukkan Tidak Valid \n3. Mohon Cek Saldo","ERROR",0);
        }
    }//GEN-LAST:event_TransferActionPerformed

    private void PenarikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenarikanActionPerformed
        // TODO add your handling code here:
        tarik = JOptionPane.showInputDialog(null,"Masukkan jumlah penarikan: " ); //menabung
    t = Integer.parseInt(tarik);
    if (t%100!=0){
        JOptionPane.showMessageDialog(null,"Mesin ATM  BRI tidak menerima uang koin "
        + "\nSilahkan ulangi kembali","Transaksi GAGAL", 0);
        }else if (t>tab) {
            JOptionPane.showMessageDialog(null,"Maaf Jumlah Saldo Anda Kurang\nSilahkan Lakukan Penyetoran!!!","ERROR",0);
        }else if (t<50000) {
            JOptionPane.showMessageDialog(null,"Jumlah Penarikan Minimal Rp,50000","ERROR",0);
        }else if (t>=50000){
            JOptionPane.showMessageDialog(null,"Anda menarik sebesar : " + t);
            tab = tab-t;
            z=JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain?","ATM BNI SYARIAH-BOJONEGORO"
                                ,JOptionPane.YES_NO_OPTION, 3);
                if (z==0){
                    pass = JOptionPane.showInputDialog(null,"Masukkan Password : " );
                    x = Integer.parseInt(pass);
                    if(x==1234){
                        JOptionPane.showMessageDialog(null,"Password Benar, \nSilahkan Click OK");
                    }else{
                        JOptionPane.showMessageDialog(null,"Password Salah","ERROR",0);
                        dispose();
                    }
                }else{
                    this.dispose();
                }
            }
    }//GEN-LAST:event_PenarikanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For detaiPenyetorandownload.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
            }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Bantuan;
    private javax.swing.JToggleButton ISaldo;
    private javax.swing.JToggleButton Penarikan;
    private javax.swing.JToggleButton Penyetoran;
    private javax.swing.JToggleButton Transfer;
    private javax.swing.JToggleButton bExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
